version: '2.0'

services:
  registry:
    restart: always
    image: registry:2.6.2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/live/assistance.bg/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/live/assistance.bg/privkey.pem
    volumes:
      - /var/lib/registry-data:/var/lib/registry
      - /etc/letsencrypt/:/certs
    ports:
      - 5555:5000

  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8888:80
    environment:
      - REGISTRY_TITLE=Minerva's Private Registry
      - REGISTRY_URL=https://registry:5000
    depends_on:
      - registry
